version: "3.9"
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/elasticsearch_exam
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  es:
    build: ./docker/es
    hostname: doc-elastic101
    container_name: es
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    environment:
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_HOSTS: http://doc-elastic101:9200
    ports:
      - "5601:5601"
    depends_on:
      - es